<?php
return [
    'APP_URL' => 'https://api.vbcbharat.com',
    'FRONTEND_URL' => 'https://www.vbcbharat.com',
    'ALLOWED_ORIGIN' => 'https://www.vbcbharat.com',
    'BRAND_NAME' => 'VB Consultants',
    'REGISTERED_BUSINESS_NAME' => 'Veedanath Business Consultants',
    'OFFICE_ADDRESS' => 'Bhubaneswar, Odisha',
    'PUBLIC_PHONE' => '+91 73278 54329',
    'WHATSAPP_NUMBER' => '919000000000',
    'ADMIN_EMAIL' => 'consult@vbcbharat.com',
    'MEDIA_BASE_URL' => 'https://api.vbcbharat.com/media',
    'app_env' => 'production',
    'app_secret' => 'change-this-long-random-secret',
    'INSTALLER_SECRET' => 'change-this-one-time-installer-secret',
    'MIN_PASSWORD_LENGTH' => 4,
    'SMTP_ENABLED' => true,
    'SMTP_HOST' => 'smtp.hostinger.com',
    'SMTP_PORT' => 465,
    'SMTP_ENCRYPTION' => 'ssl',
    'SMTP_USERNAME' => 'consult@vbcbharat.com',
    'SMTP_PASSWORD' => 'your_mailbox_password',
    'SMTP_FROM_EMAIL' => 'consult@vbcbharat.com',
    'SMTP_FROM_NAME' => 'VB Consultants',
    'SMTP_REPLY_TO' => 'consult@vbcbharat.com',
    'MAIL_DEBUG' => false,
    'RAZORPAY_ENABLED' => true,
    'MANUAL_PAYMENT_ENABLED' => true,
    'MANUAL_UPI_ID' => 'payments@exampleupi',
    'FRONTEND_REVALIDATE_URL' => 'https://www.vbcbharat.com/api/revalidate',
    'FRONTEND_REVALIDATE_SECRET' => 'change_this_if_revalidation_is_used',
    'SESSION_COOKIE_NAME' => 'vbc_session',
    'SESSION_COOKIE_DOMAIN' => '.vbcbharat.com',
    'SESSION_DAYS' => 30,
    'mysql' => [
        'host' => 'localhost',
        'database' => 'hostinger_database',
        'user' => 'hostinger_user',
        'password' => 'hostinger_password',
        'charset' => 'utf8mb4',
    ],
    'razorpay' => [
        'key_id' => 'rzp_test_xxxxxxxxxxxxx',
        'key_secret' => 'razorpay_secret',
        'webhook_secret' => 'razorpay_webhook_secret',
    ],
    'upload_dir' => __DIR__ . '/uploads',
    'media_dir' => __DIR__ . '/media',
    'max_upload_size' => 8 * 1024 * 1024,
    'max_media_size' => 4 * 1024 * 1024,
    'admin_session_timeout' => 60 * 60 * 8,
];
